# Generated by Django 3.0.8 on 2020-07-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('check_code', models.CharField(max_length=50)),
                ('checked', models.SmallIntegerField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('account_id', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
                ('username_id', models.ForeignKey(db_column='username_id', on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='username_id',
            field=models.ForeignKey(db_column='username_id', on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
